name: Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          CRUMB=$(curl -s -u "$JENKINS_USER:$JENKINS_TOKEN" \
            "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")

          curl -u "$JENKINS_USER:$JENKINS_TOKEN" -H "$CRUMB" \
               -X POST "$JENKINS_URL/job/Kuruma%20Tools/job/test/build?token=12345678"
